import './globals.css'
import type { Metadata } from 'next'
import { Inter as FontSans } from "next/font/google"
import ThemeRegister from '@/components/ThemeRegister'
import { cn } from '@/lib/utils';

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <ThemeRegister>
        <body className={cn(
          " min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
          <div className='h-screen'>
            {children}
          </div>
        </body>
      </ThemeRegister>
    </html>
  )
}
