// import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegister from '@/components/ThemeRegister'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <ThemeRegister>
        <body className={inter.className} style={{ margin: 0 }}>{children}</body>
      </ThemeRegister>
    </html>
  )
}
